on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  k6_transpile_bundle_test:
    name: Transpile, bundle and run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18
        run: |
          echo "Using node.js $(node -v) in this action"
          echo "Installing nvm"
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
          source ~/.nvm/nvm.sh
          echo "Setting default node version to 18"
          nvm install 18
          nvm use 18
          echo "Using node.js $(node -v) in this action"

      - name: Check version
        run: node --version

      - name: Install dependencies
        run: |
          yarn --frozen-lockfile

      - name: Transpile and bundle test script
        run: yarn build

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: dist/get-200-status-test.js
